services:
  postgres:
    image: postgres:17
    container_name: flower-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: flower
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: j7gks8In
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: