"""add subcategories

Revision ID: 689d68cf4b8a
Revises: 38f2aeff264f
Create Date: 2026-09-13 19:54:05.528796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689d68cf4b8a'
down_revision: Union[str, Sequence[str], None] = '38f2aeff264f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parentId', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_categories_parentId'), 'categories', ['parentId'], unique=False)
    op.create_foreign_key(None, 'categories', 'categories', ['parentId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_parentId_fkey', 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_parentId'), table_name='categories')
    op.drop_column('categories', 'parentId')
    # ### end Alembic commands ###
