"""flowers

Revision ID: b3ce41b4eaf4
Revises: ab93d81071b7
Create Date: 2026-09-21 10:25:15.007951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ce41b4eaf4'
down_revision: Union[str, Sequence[str], None] = 'ab93d81071b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flowers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_flowers',
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('flowerId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flowerId'], ['flowers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('productId', 'flowerId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_flowers')
    op.drop_table('flowers')
    # ### end Alembic commands ###
